[package]
name = "xkcd"
version = "0.1.0"
authors = ["Jacob Shin <jacobshin313@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.0"
select = "0.4.3"
image = "0.22.4"
clap = "2.33.0"
